[package]
name = "Originmate"
version = "2.6.0"
authors = [
    "David Lucid <david@pentagon.xyz>",
    "Jakub Labor <jakub@originbyte.io>",
    "Michael Bausano <michael@originbyte.io>",
    "Nuno Boavida <nuno@originbyte.io>"
]

[addresses]
originmate = "0x92ae744e95056f895f2ffec7c75c9d86d7651ec7"

[dependencies.Sui]
git = "git@github.com:MystenLabs/sui.git"
subdir = "crates/sui-framework/sui-framework"
# devnet-0.27.0
rev = "releases/sui-v0.29.0-release"
