[package]
name = "Originmate"
version = "2.6.0"
authors = [
    "David Lucid <david@pentagon.xyz>",
    "Jakub Labor <jakub@originbyte.io>",
    "Michael Bausano <michael@originbyte.io>",
    "Nuno Boavida <nuno@originbyte.io>"
]

[addresses]
# not published
originmate = "0x0"

[dependencies.Sui]
git = "git@github.com:MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# devnet-0.27.0
rev = "devnet"
