[package]
name = "Originmate"
version = "2.6.0"
authors = [
    "David Lucid <david@pentagon.xyz>",
    "Jakub Labor <jakub@originbyte.io>",
    "Michael Bausano <michael@originbyte.io>",
    "Nuno Boavida <nuno@originbyte.io>"
]

published-at = "0x32e32cc9ff3f42a1110670fe68d3ce04320a6381beedf1c2e54cadb973706614"

[addresses]
originmate = "0x32e32cc9ff3f42a1110670fe68d3ce04320a6381beedf1c2e54cadb973706614"

[dependencies.Sui]
git = "git@github.com:MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# devnet-0.27.0
rev = "testnet"
